apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "argocd-def"
spec:
  destination:
    namespace: binco97-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/base
    repoURL: https://github.com/BlackMamba97s/argocd-def
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  createNamespace: true

